# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'Pokemon', type: :request do
  describe '#index' do
    it 'get pokemon list', :vcr do
      get api_pokemons_path
      expect(response).to have_http_status(:success)
      expect(response.parsed_body).to match({'results' =>
      [{'name' => 'フシギダネ', 'url' => 'https://pokeapi.co/api/v2/pokemon/1/', 'id' => 1},
       {'name' => 'フシギソウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/2/', 'id' => 2},
       {'name' => 'フシギバナ', 'url' => 'https://pokeapi.co/api/v2/pokemon/3/', 'id' => 3},
       {'name' => 'ヒトカゲ', 'url' => 'https://pokeapi.co/api/v2/pokemon/4/', 'id' => 4},
       {'name' => 'リザード', 'url' => 'https://pokeapi.co/api/v2/pokemon/5/', 'id' => 5},
       {'name' => 'リザードン', 'url' => 'https://pokeapi.co/api/v2/pokemon/6/', 'id' => 6},
       {'name' => 'ゼニガメ', 'url' => 'https://pokeapi.co/api/v2/pokemon/7/', 'id' => 7},
       {'name' => 'カメール', 'url' => 'https://pokeapi.co/api/v2/pokemon/8/', 'id' => 8},
       {'name' => 'カメックス', 'url' => 'https://pokeapi.co/api/v2/pokemon/9/', 'id' => 9},
       {'name' => 'キャタピー', 'url' => 'https://pokeapi.co/api/v2/pokemon/10/', 'id' => 10},
       {'name' => 'トランセル', 'url' => 'https://pokeapi.co/api/v2/pokemon/11/', 'id' => 11},
       {'name' => 'バタフリー', 'url' => 'https://pokeapi.co/api/v2/pokemon/12/', 'id' => 12},
       {'name' => 'ビードル', 'url' => 'https://pokeapi.co/api/v2/pokemon/13/', 'id' => 13},
       {'name' => 'コクーン', 'url' => 'https://pokeapi.co/api/v2/pokemon/14/', 'id' => 14},
       {'name' => 'スピアー', 'url' => 'https://pokeapi.co/api/v2/pokemon/15/', 'id' => 15},
       {'name' => 'ポッポ', 'url' => 'https://pokeapi.co/api/v2/pokemon/16/', 'id' => 16},
       {'name' => 'ピジョン', 'url' => 'https://pokeapi.co/api/v2/pokemon/17/', 'id' => 17},
       {'name' => 'ピジョット', 'url' => 'https://pokeapi.co/api/v2/pokemon/18/', 'id' => 18},
       {'name' => 'コラッタ', 'url' => 'https://pokeapi.co/api/v2/pokemon/19/', 'id' => 19},
       {'name' => 'ラッタ', 'url' => 'https://pokeapi.co/api/v2/pokemon/20/', 'id' => 20},
       {'name' => 'オニスズメ', 'url' => 'https://pokeapi.co/api/v2/pokemon/21/', 'id' => 21},
       {'name' => 'オニドリル', 'url' => 'https://pokeapi.co/api/v2/pokemon/22/', 'id' => 22},
       {'name' => 'アーボ', 'url' => 'https://pokeapi.co/api/v2/pokemon/23/', 'id' => 23},
       {'name' => 'アーボック', 'url' => 'https://pokeapi.co/api/v2/pokemon/24/', 'id' => 24},
       {'name' => 'ピカチュウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/25/', 'id' => 25},
       {'name' => 'ライチュウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/26/', 'id' => 26},
       {'name' => 'サンド', 'url' => 'https://pokeapi.co/api/v2/pokemon/27/', 'id' => 27},
       {'name' => 'サンドパン', 'url' => 'https://pokeapi.co/api/v2/pokemon/28/', 'id' => 28},
       {'name' => 'ニドラン♀', 'url' => 'https://pokeapi.co/api/v2/pokemon/29/', 'id' => 29},
       {'name' => 'ニドリーナ', 'url' => 'https://pokeapi.co/api/v2/pokemon/30/', 'id' => 30},
       {'name' => 'ニドクイン', 'url' => 'https://pokeapi.co/api/v2/pokemon/31/', 'id' => 31},
       {'name' => 'ニドラン♂', 'url' => 'https://pokeapi.co/api/v2/pokemon/32/', 'id' => 32},
       {'name' => 'ニドリーノ', 'url' => 'https://pokeapi.co/api/v2/pokemon/33/', 'id' => 33},
       {'name' => 'ニドキング', 'url' => 'https://pokeapi.co/api/v2/pokemon/34/', 'id' => 34},
       {'name' => 'ピッピ', 'url' => 'https://pokeapi.co/api/v2/pokemon/35/', 'id' => 35},
       {'name' => 'ピクシー', 'url' => 'https://pokeapi.co/api/v2/pokemon/36/', 'id' => 36},
       {'name' => 'ロコン', 'url' => 'https://pokeapi.co/api/v2/pokemon/37/', 'id' => 37},
       {'name' => 'キュウコン', 'url' => 'https://pokeapi.co/api/v2/pokemon/38/', 'id' => 38},
       {'name' => 'プリン', 'url' => 'https://pokeapi.co/api/v2/pokemon/39/', 'id' => 39},
       {'name' => 'プクリン', 'url' => 'https://pokeapi.co/api/v2/pokemon/40/', 'id' => 40},
       {'name' => 'ズバット', 'url' => 'https://pokeapi.co/api/v2/pokemon/41/', 'id' => 41},
       {'name' => 'ゴルバット', 'url' => 'https://pokeapi.co/api/v2/pokemon/42/', 'id' => 42},
       {'name' => 'ナゾノクサ', 'url' => 'https://pokeapi.co/api/v2/pokemon/43/', 'id' => 43},
       {'name' => 'クサイハナ', 'url' => 'https://pokeapi.co/api/v2/pokemon/44/', 'id' => 44},
       {'name' => 'ラフレシア', 'url' => 'https://pokeapi.co/api/v2/pokemon/45/', 'id' => 45},
       {'name' => 'パラス', 'url' => 'https://pokeapi.co/api/v2/pokemon/46/', 'id' => 46},
       {'name' => 'パラセクト', 'url' => 'https://pokeapi.co/api/v2/pokemon/47/', 'id' => 47},
       {'name' => 'コンパン', 'url' => 'https://pokeapi.co/api/v2/pokemon/48/', 'id' => 48},
       {'name' => 'モルフォン', 'url' => 'https://pokeapi.co/api/v2/pokemon/49/', 'id' => 49},
       {'name' => 'ディグダ', 'url' => 'https://pokeapi.co/api/v2/pokemon/50/', 'id' => 50},
       {'name' => 'ダグトリオ', 'url' => 'https://pokeapi.co/api/v2/pokemon/51/', 'id' => 51},
       {'name' => 'ニャース', 'url' => 'https://pokeapi.co/api/v2/pokemon/52/', 'id' => 52},
       {'name' => 'ペルシアン', 'url' => 'https://pokeapi.co/api/v2/pokemon/53/', 'id' => 53},
       {'name' => 'コダック', 'url' => 'https://pokeapi.co/api/v2/pokemon/54/', 'id' => 54},
       {'name' => 'ゴルダック', 'url' => 'https://pokeapi.co/api/v2/pokemon/55/', 'id' => 55},
       {'name' => 'マンキー', 'url' => 'https://pokeapi.co/api/v2/pokemon/56/', 'id' => 56},
       {'name' => 'オコリザル', 'url' => 'https://pokeapi.co/api/v2/pokemon/57/', 'id' => 57},
       {'name' => 'ガーディ', 'url' => 'https://pokeapi.co/api/v2/pokemon/58/', 'id' => 58},
       {'name' => 'ウインディ', 'url' => 'https://pokeapi.co/api/v2/pokemon/59/', 'id' => 59},
       {'name' => 'ニョロモ', 'url' => 'https://pokeapi.co/api/v2/pokemon/60/', 'id' => 60},
       {'name' => 'ニョロゾ', 'url' => 'https://pokeapi.co/api/v2/pokemon/61/', 'id' => 61},
       {'name' => 'ニョロボン', 'url' => 'https://pokeapi.co/api/v2/pokemon/62/', 'id' => 62},
       {'name' => 'ケーシィ', 'url' => 'https://pokeapi.co/api/v2/pokemon/63/', 'id' => 63},
       {'name' => 'ユンゲラー', 'url' => 'https://pokeapi.co/api/v2/pokemon/64/', 'id' => 64},
       {'name' => 'フーディン', 'url' => 'https://pokeapi.co/api/v2/pokemon/65/', 'id' => 65},
       {'name' => 'ワンリキー', 'url' => 'https://pokeapi.co/api/v2/pokemon/66/', 'id' => 66},
       {'name' => 'ゴーリキー', 'url' => 'https://pokeapi.co/api/v2/pokemon/67/', 'id' => 67},
       {'name' => 'カイリキー', 'url' => 'https://pokeapi.co/api/v2/pokemon/68/', 'id' => 68},
       {'name' => 'マダツボミ', 'url' => 'https://pokeapi.co/api/v2/pokemon/69/', 'id' => 69},
       {'name' => 'ウツドン', 'url' => 'https://pokeapi.co/api/v2/pokemon/70/', 'id' => 70},
       {'name' => 'ウツドンズク', 'url' => 'https://pokeapi.co/api/v2/pokemon/71/', 'id' => 71},
       {'name' => 'メノクラゲ', 'url' => 'https://pokeapi.co/api/v2/pokemon/72/', 'id' => 72},
       {'name' => 'ドククラゲ', 'url' => 'https://pokeapi.co/api/v2/pokemon/73/', 'id' => 73},
       {'name' => 'イシツブテ', 'url' => 'https://pokeapi.co/api/v2/pokemon/74/', 'id' => 74},
       {'name' => 'ゴローン', 'url' => 'https://pokeapi.co/api/v2/pokemon/75/', 'id' => 75},
       {'name' => 'ゴローニャ', 'url' => 'https://pokeapi.co/api/v2/pokemon/76/', 'id' => 76},
       {'name' => 'ポニータ', 'url' => 'https://pokeapi.co/api/v2/pokemon/77/', 'id' => 77},
       {'name' => 'ギャロップ', 'url' => 'https://pokeapi.co/api/v2/pokemon/78/', 'id' => 78},
       {'name' => 'ヤドン', 'url' => 'https://pokeapi.co/api/v2/pokemon/79/', 'id' => 79},
       {'name' => 'ヤドラン', 'url' => 'https://pokeapi.co/api/v2/pokemon/80/', 'id' => 80},
       {'name' => 'コイル', 'url' => 'https://pokeapi.co/api/v2/pokemon/81/', 'id' => 81},
       {'name' => 'レアコイル', 'url' => 'https://pokeapi.co/api/v2/pokemon/82/', 'id' => 82},
       {'name' => 'カモネギ', 'url' => 'https://pokeapi.co/api/v2/pokemon/83/', 'id' => 83},
       {'name' => 'ドードー', 'url' => 'https://pokeapi.co/api/v2/pokemon/84/', 'id' => 84},
       {'name' => 'ドードリオ', 'url' => 'https://pokeapi.co/api/v2/pokemon/85/', 'id' => 85},
       {'name' => 'パウワウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/86/', 'id' => 86},
       {'name' => 'ジュゴン', 'url' => 'https://pokeapi.co/api/v2/pokemon/87/', 'id' => 87},
       {'name' => 'ベトベター', 'url' => 'https://pokeapi.co/api/v2/pokemon/88/', 'id' => 88},
       {'name' => 'ベトベトン', 'url' => 'https://pokeapi.co/api/v2/pokemon/89/', 'id' => 89},
       {'name' => 'シェルダー', 'url' => 'https://pokeapi.co/api/v2/pokemon/90/', 'id' => 90},
       {'name' => 'パルシェン', 'url' => 'https://pokeapi.co/api/v2/pokemon/91/', 'id' => 91},
       {'name' => 'ゴース', 'url' => 'https://pokeapi.co/api/v2/pokemon/92/', 'id' => 92},
       {'name' => 'ゴースト', 'url' => 'https://pokeapi.co/api/v2/pokemon/93/', 'id' => 93},
       {'name' => 'ゲンガー', 'url' => 'https://pokeapi.co/api/v2/pokemon/94/', 'id' => 94},
       {'name' => 'イワーク', 'url' => 'https://pokeapi.co/api/v2/pokemon/95/', 'id' => 95},
       {'name' => 'スリープ', 'url' => 'https://pokeapi.co/api/v2/pokemon/96/', 'id' => 96},
       {'name' => 'スリーパー', 'url' => 'https://pokeapi.co/api/v2/pokemon/97/', 'id' => 97},
       {'name' => 'クラブ', 'url' => 'https://pokeapi.co/api/v2/pokemon/98/', 'id' => 98},
       {'name' => 'キングラー', 'url' => 'https://pokeapi.co/api/v2/pokemon/99/', 'id' => 99},
       {'name' => 'ビリリダマ', 'url' => 'https://pokeapi.co/api/v2/pokemon/100/', 'id' => 100},
       {'name' => 'マルマイン', 'url' => 'https://pokeapi.co/api/v2/pokemon/101/', 'id' => 101},
       {'name' => 'タマタマ', 'url' => 'https://pokeapi.co/api/v2/pokemon/102/', 'id' => 102},
       {'name' => 'ナッシー', 'url' => 'https://pokeapi.co/api/v2/pokemon/103/', 'id' => 103},
       {'name' => 'カラカラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/104/', 'id' => 104},
       {'name' => 'ガラガラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/105/', 'id' => 105},
       {'name' => 'サワムラー', 'url' => 'https://pokeapi.co/api/v2/pokemon/106/', 'id' => 106},
       {'name' => 'エビワラー', 'url' => 'https://pokeapi.co/api/v2/pokemon/107/', 'id' => 107},
       {'name' => 'ベロリンガ', 'url' => 'https://pokeapi.co/api/v2/pokemon/108/', 'id' => 108},
       {'name' => 'ドガース', 'url' => 'https://pokeapi.co/api/v2/pokemon/109/', 'id' => 109},
       {'name' => 'マタドガス', 'url' => 'https://pokeapi.co/api/v2/pokemon/110/', 'id' => 110},
       {'name' => 'サイホーン', 'url' => 'https://pokeapi.co/api/v2/pokemon/111/', 'id' => 111},
       {'name' => 'サイドン', 'url' => 'https://pokeapi.co/api/v2/pokemon/112/', 'id' => 112},
       {'name' => 'ラッキー', 'url' => 'https://pokeapi.co/api/v2/pokemon/113/', 'id' => 113},
       {'name' => 'モンジャラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/114/', 'id' => 114},
       {'name' => 'ガルーラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/115/', 'id' => 115},
       {'name' => 'タッツー', 'url' => 'https://pokeapi.co/api/v2/pokemon/116/', 'id' => 116},
       {'name' => 'シードラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/117/', 'id' => 117},
       {'name' => 'トサキント', 'url' => 'https://pokeapi.co/api/v2/pokemon/118/', 'id' => 118},
       {'name' => 'アズマオウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/119/', 'id' => 119},
       {'name' => 'ヒトデマン', 'url' => 'https://pokeapi.co/api/v2/pokemon/120/', 'id' => 120},
       {'name' => 'スターミー', 'url' => 'https://pokeapi.co/api/v2/pokemon/121/', 'id' => 121},
       {'name' => 'バリヤード', 'url' => 'https://pokeapi.co/api/v2/pokemon/122/', 'id' => 122},
       {'name' => 'ストライク', 'url' => 'https://pokeapi.co/api/v2/pokemon/123/', 'id' => 123},
       {'name' => 'ルージュラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/124/', 'id' => 124},
       {'name' => 'エレブー', 'url' => 'https://pokeapi.co/api/v2/pokemon/125/', 'id' => 125},
       {'name' => 'ブーバー', 'url' => 'https://pokeapi.co/api/v2/pokemon/126/', 'id' => 126},
       {'name' => 'カイロス', 'url' => 'https://pokeapi.co/api/v2/pokemon/127/', 'id' => 127},
       {'name' => 'ケンタロス', 'url' => 'https://pokeapi.co/api/v2/pokemon/128/', 'id' => 128},
       {'name' => 'コイキング', 'url' => 'https://pokeapi.co/api/v2/pokemon/129/', 'id' => 129},
       {'name' => 'ギャラドス', 'url' => 'https://pokeapi.co/api/v2/pokemon/130/', 'id' => 130},
       {'name' => 'ラプラス', 'url' => 'https://pokeapi.co/api/v2/pokemon/131/', 'id' => 131},
       {'name' => 'メタモン', 'url' => 'https://pokeapi.co/api/v2/pokemon/132/', 'id' => 132},
       {'name' => 'イーブイ', 'url' => 'https://pokeapi.co/api/v2/pokemon/133/', 'id' => 133},
       {'name' => 'シャワーズ', 'url' => 'https://pokeapi.co/api/v2/pokemon/134/', 'id' => 134},
       {'name' => 'サンダース', 'url' => 'https://pokeapi.co/api/v2/pokemon/135/', 'id' => 135},
       {'name' => 'ブースター', 'url' => 'https://pokeapi.co/api/v2/pokemon/136/', 'id' => 136},
       {'name' => 'ポリゴン', 'url' => 'https://pokeapi.co/api/v2/pokemon/137/', 'id' => 137},
       {'name' => 'オムナイト', 'url' => 'https://pokeapi.co/api/v2/pokemon/138/', 'id' => 138},
       {'name' => 'オムスター', 'url' => 'https://pokeapi.co/api/v2/pokemon/139/', 'id' => 139},
       {'name' => 'カブト', 'url' => 'https://pokeapi.co/api/v2/pokemon/140/', 'id' => 140},
       {'name' => 'カブトプス', 'url' => 'https://pokeapi.co/api/v2/pokemon/141/', 'id' => 141},
       {'name' => 'プテラ', 'url' => 'https://pokeapi.co/api/v2/pokemon/142/', 'id' => 142},
       {'name' => 'カビゴン', 'url' => 'https://pokeapi.co/api/v2/pokemon/143/', 'id' => 143},
       {'name' => 'フリーザー', 'url' => 'https://pokeapi.co/api/v2/pokemon/144/', 'id' => 144},
       {'name' => 'サンダー', 'url' => 'https://pokeapi.co/api/v2/pokemon/145/', 'id' => 145},
       {'name' => 'ファイヤー', 'url' => 'https://pokeapi.co/api/v2/pokemon/146/', 'id' => 146},
       {'name' => 'ミニリュウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/147/', 'id' => 147},
       {'name' => 'ハクリュー', 'url' => 'https://pokeapi.co/api/v2/pokemon/148/', 'id' => 148},
       {'name' => 'カイリュー', 'url' => 'https://pokeapi.co/api/v2/pokemon/149/', 'id' => 149},
       {'name' => 'ミュウツー', 'url' => 'https://pokeapi.co/api/v2/pokemon/150/', 'id' => 150},
       {'name' => 'ミュウ', 'url' => 'https://pokeapi.co/api/v2/pokemon/151/', 'id' => 151}]})
    end
  end

  describe '#show' do
    let(:id) { 25 } # ピカチュウ

    it 'get pokemon data', :vcr do
      get api_pokemon_path(id)
      expect(response).to have_http_status(:success)
      expect(response.parsed_body).to match(
        {'id' => 25,
         'name' => 'ピカチュウ',
         'types' => [{'slot' => 1, 'name' => 'でんき', 'url' => 'https://pokeapi.co/api/v2/type/13/'}],
         'status' =>
       {'hp' => {'base_stat' => 35, 'effort' => 0},
        'attack' => {'base_stat' => 55, 'effort' => 0},
        'defense' => {'base_stat' => 40, 'effort' => 0},
        'special_attack' => {'base_stat' => 50, 'effort' => 0},
        'special_defense' => {'base_stat' => 50, 'effort' => 0},
        'speed' => {'base_stat' => 90, 'effort' => 2}},
         'sprites' =>
       {'back_female' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/25.png',
        'back_shiny_female' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/25.png',
        'back_default' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',
        'front_female' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/female/25.png',
        'front_shiny_female' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/female/25.png',
        'back_shiny' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/25.png',
        'front_default' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',
        'front_shiny' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/shiny/25.png'},
         'flavor_text' => "森に　棲む　ポケモン。　ほっぺの\nふくろは　電気を　ためるので\n触ると　パチパチ　痺れるぞ。",
         'moves' =>
       [{'name' => 'めいそう', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'かみなりパンチ', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'あなをほる', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'どくどく', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'ひかりのかべ', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'リフレクター', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'ねむる', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'みがわり', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'まもる', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'アイアンテール', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'からげんき', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'てだすけ', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'れんぞくぎり', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'ネコにこばん', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'ずつき', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'ちきゅうなげ', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => '１０まんボルト', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'でんじは', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'かみなり', 'level_learned_at' => 0, 'move_learn_method' => 'machine'},
        {'name' => 'なきごえ', 'level_learned_at' => 1, 'move_learn_method' => 'level-up'},
        {'name' => 'でんきショック', 'level_learned_at' => 1, 'move_learn_method' => 'level-up'},
        {'name' => 'しっぽをふる', 'level_learned_at' => 3, 'move_learn_method' => 'level-up'},
        {'name' => 'でんこうせっか', 'level_learned_at' => 6, 'move_learn_method' => 'level-up'},
        {'name' => 'にどげり', 'level_learned_at' => 9, 'move_learn_method' => 'level-up'},
        {'name' => 'かげぶんしん', 'level_learned_at' => 12, 'move_learn_method' => 'level-up'},
        {'name' => 'でんじは', 'level_learned_at' => 15, 'move_learn_method' => 'level-up'},
        {'name' => 'ひかりのかべ', 'level_learned_at' => 18, 'move_learn_method' => 'level-up'},
        {'name' => '１０まんボルト', 'level_learned_at' => 21, 'move_learn_method' => 'level-up'},
        {'name' => 'たたきつける', 'level_learned_at' => 24, 'move_learn_method' => 'level-up'},
        {'name' => 'こうそくいどう', 'level_learned_at' => 27, 'move_learn_method' => 'level-up'},
        {'name' => 'かみなり', 'level_learned_at' => 30, 'move_learn_method' => 'level-up'}],
         'version' => 'lets-go-pikachu'}
      )
    end

    context 'get pokemon data which has moves with same names' do
      let(:id) { 3 } # フシギバナ

      it '', :vcr do
        get api_pokemon_path(id)
        expect(response).to have_http_status(:success)
        expect(response.parsed_body['moves']).to include(
          {'name' => 'はなびらのまい', 'level_learned_at' => 0, 'move_learn_method' => 'level-up'},
          {'name' => 'はなびらのまい', 'level_learned_at' => 1, 'move_learn_method' => 'level-up'}
        )
      end
    end
  end
end
