# frozen_string_literal: true

require 'rails_helper'

RSpec.describe 'Pokemon', type: :request do
  describe '#index' do
    it 'get pokemon list', :vcr do
      get api_pokemons_path, params: {pokedexes: ['letsgo-kanto']}
      expect(response).to have_http_status(:success)
      body = response.parsed_body.first
      expect(body[:pokemons].size).to eq 153
      expect(body['pokemons']).to include(
        {
          'id' => 1,
          'name' => 'bulbasaur',
          'display_name' => 'フシギダネ',
          'pokedex_number' => 1
        },
        {
          'id' => 808,
          'name' => 'meltan',
          'display_name' => 'メルタン',
          'pokedex_number' => 152
        }
      )
    end
  end

  describe '#show', :vcr do
    let(:id) { 25 } # ピカチュウ

    it 'get pokemon data' do
      get api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
      expect(response).to have_http_status(:success)
      p response.parsed_body
      expect(response.parsed_body).to match(
        {
          'id' => 25,
          'species_id' => 25,
          'name' => 'ピカチュウ',
          'types' => [{'slot' => 1, 'name' => 'でんき'}],
          'status' => [{'name' => 'hp', 'label' => 'HP', 'base_stat' => 35, 'effort' => 0}, {'name' => 'attack', 'label' => 'こうげき', 'base_stat' => 55, 'effort' => 0}, {'name' => 'defense', 'label' => 'ぼうぎょ', 'base_stat' => 40, 'effort' => 0}, {'name' => 'special_attack', 'label' => 'とくこう', 'base_stat' => 50, 'effort' => 0}, {'name' => 'special_defense', 'label' => 'とくぼう', 'base_stat' => 50, 'effort' => 0}, {'name' => 'speed', 'label' => 'すばやさ', 'base_stat' => 90, 'effort' => 2}],
          'sprites' => {'front_default' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png'},
          'abilities' => [{'name' => 'せいでんき', 'is_hidden' => false, 'flavor_text' => "静電気を　体に　まとい\n触った　相手を\nまひさせる　ことがある。"}, {'name' => 'ひらいしん', 'is_hidden' => true, 'flavor_text' => "でんきタイプの　技を　自分に\n寄せつけ　ダメージを　受けずに\n特攻が　上がる。"}],
          'flavor_text' => "森に　棲む　ポケモン。　ほっぺの\nふくろは　電気を　ためるので\n触ると　パチパチ　痺れるぞ。",
          'moves' => [{'id' => 45, 'move_learn_method' => 'level-up', 'level' => 1, 'name' => 'なきごえ', 'power' => nil, 'accuracy' => 100, 'pp' => 40, 'type' => 'ノーマル', 'flavor_text' => "かわいい　なきごえを　聞かせて\n気を　ひき　油断を　させて\n相手の　攻撃を　さげる。"}, {'id' => 84, 'move_learn_method' => 'level-up', 'level' => 1, 'name' => 'でんきショック', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'でんき', 'flavor_text' => "電気の　刺激を\n相手に　浴びせて　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 39, 'move_learn_method' => 'level-up', 'level' => 3, 'name' => 'しっぽをふる', 'power' => nil, 'accuracy' => 100, 'pp' => 30, 'type' => 'ノーマル', 'flavor_text' => "しっぽを　左右に　かわいく　ふって\n油断を　誘う。\n相手の　防御を　さげる。"}, {'id' => 98, 'move_learn_method' => 'level-up', 'level' => 6, 'name' => 'でんこうせっか', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'ノーマル', 'flavor_text' => "目にも　留まらぬ　ものすごい　速さで\n相手に　つっこむ。\n必ず　先制攻撃　できる。"}, {'id' => 24, 'move_learn_method' => 'level-up', 'level' => 9, 'name' => 'にどげり', 'power' => 30, 'accuracy' => 100, 'pp' => 30, 'type' => 'かくとう', 'flavor_text' => "２本の　足で　相手を　けとばして\n攻撃する。　２回連続で\nダメージを　与える。"}, {'id' => 104, 'move_learn_method' => 'level-up', 'level' => 12, 'name' => 'かげぶんしん', 'power' => nil, 'accuracy' => nil, 'pp' => 15, 'type' => 'ノーマル', 'flavor_text' => "素早い　動きで　分身を　つくり\n相手を　まどわせて\n回避率を　あげる。"}, {'id' => 86, 'move_learn_method' => 'level-up', 'level' => 15, 'name' => 'でんじは', 'power' => nil, 'accuracy' => 90, 'pp' => 20, 'type' => 'でんき', 'flavor_text' => "弱い　電撃を　浴びせることで\n相手を　まひ状態に　する。"}, {'id' => 113, 'move_learn_method' => 'level-up', 'level' => 18, 'name' => 'ひかりのかべ', 'power' => nil, 'accuracy' => nil, 'pp' => 30, 'type' => 'エスパー', 'flavor_text' => "５ターンの　間　不思議な　かべで\n相手から　受ける　特殊攻撃の\nダメージを　弱める。"}, {'id' => 85, 'move_learn_method' => 'level-up', 'level' => 21, 'name' => '１０まんボルト', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'でんき', 'flavor_text' => "強い　電撃を\n相手に　浴びせて　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 21, 'move_learn_method' => 'level-up', 'level' => 24, 'name' => 'たたきつける', 'power' => 80, 'accuracy' => 75, 'pp' => 20, 'type' => 'ノーマル', 'flavor_text' => "長い　しっぽや　つるなどを　使い\n相手を　たたきつけて　攻撃する。"}, {'id' => 97, 'move_learn_method' => 'level-up', 'level' => 27, 'name' => 'こうそくいどう', 'power' => nil, 'accuracy' => nil, 'pp' => 30, 'type' => 'エスパー', 'flavor_text' => "力を　ぬいて　体を　軽くして\n高速で　動く。\n自分の　素早さを　ぐーんと　あげる。"}, {'id' => 87, 'move_learn_method' => 'level-up', 'level' => 30, 'name' => 'かみなり', 'power' => 110, 'accuracy' => 70, 'pp' => 10, 'type' => 'でんき', 'flavor_text' => "激しい　雷を\n相手に　落として　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 6, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'ネコにこばん', 'power' => 40, 'accuracy' => 100, 'pp' => 20, 'type' => 'ノーマル', 'flavor_text' => "相手の　体に\n小判を　投げつけて　攻撃する。\n戦闘の　あとで　お金が　もらえる。"}, {'id' => 9, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'かみなりパンチ', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'でんき', 'flavor_text' => "電撃を　こめた　パンチで\n相手を　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 29, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'ずつき', 'power' => 70, 'accuracy' => 100, 'pp' => 15, 'type' => 'ノーマル', 'flavor_text' => "頭を　突きだして\nまっすぐ　つっこんで　攻撃する。\n相手を　ひるませることが　ある。"}, {'id' => 69, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'ちきゅうなげ', 'power' => nil, 'accuracy' => 100, 'pp' => 20, 'type' => 'かくとう', 'flavor_text' => "引力を　使い　投げとばす。\n自分の　レベルと　同じ　ダメージを\n相手に　与える。"}, {'id' => 85, 'move_learn_method' => 'machine', 'level' => 0, 'name' => '１０まんボルト', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'でんき', 'flavor_text' => "強い　電撃を\n相手に　浴びせて　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 86, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'でんじは', 'power' => nil, 'accuracy' => 90, 'pp' => 20, 'type' => 'でんき', 'flavor_text' => "弱い　電撃を　浴びせることで\n相手を　まひ状態に　する。"}, {'id' => 87, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'かみなり', 'power' => 110, 'accuracy' => 70, 'pp' => 10, 'type' => 'でんき', 'flavor_text' => "激しい　雷を\n相手に　落として　攻撃する。\nまひ状態に　することが　ある。"}, {'id' => 91, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'あなをほる', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'じめん', 'flavor_text' => "１ターン目に　潜り　２ターン目で\n相手を　攻撃する。"}, {'id' => 92, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'どくどく', 'power' => nil, 'accuracy' => 90, 'pp' => 10, 'type' => 'どく', 'flavor_text' => "相手を　猛毒の　状態に　する。\nターンが　すすむほど\n毒の　ダメージが　増えていく。"}, {'id' => 113, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'ひかりのかべ', 'power' => nil, 'accuracy' => nil, 'pp' => 30, 'type' => 'エスパー', 'flavor_text' => "５ターンの　間　不思議な　かべで\n相手から　受ける　特殊攻撃の\nダメージを　弱める。"}, {'id' => 115, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'リフレクター', 'power' => nil, 'accuracy' => nil, 'pp' => 20, 'type' => 'エスパー', 'flavor_text' => "５ターンの　間　不思議な　かべで\n相手から　受ける　物理攻撃の\nダメージを　弱める。"}, {'id' => 156, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'ねむる', 'power' => nil, 'accuracy' => nil, 'pp' => 5, 'type' => 'エスパー', 'flavor_text' => "２ターンの　間　眠り続ける。\n自分の　ＨＰと　状態異常を\nすべて　回復する。"}, {'id' => 164, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'みがわり', 'power' => nil, 'accuracy' => nil, 'pp' => 10, 'type' => 'ノーマル', 'flavor_text' => "自分の　ＨＰを　少し　削って\n分身を　だす。\n分身は　自分の　身代わりに　なる。"}, {'id' => 182, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'まもる', 'power' => nil, 'accuracy' => nil, 'pp' => 10, 'type' => 'ノーマル', 'flavor_text' => "相手の　攻撃を\nまったく　受けない。\n連続で　だすと　失敗しやすい。"}, {'id' => 231, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'アイアンテール', 'power' => 100, 'accuracy' => 75, 'pp' => 15, 'type' => 'はがね', 'flavor_text' => "硬い　しっぽで\n相手を　たたきつけて　攻撃する。\n相手の　防御を　さげることが　ある。"}, {'id' => 263, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'からげんき', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'ノーマル', 'flavor_text' => "自分が　毒　まひ　やけど\n状態のとき　相手に　くりだすと\n技の　威力が　２倍に　なる。"}, {'id' => 270, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'てだすけ', 'power' => nil, 'accuracy' => nil, 'pp' => 20, 'type' => 'ノーマル', 'flavor_text' => "仲間を　助ける。\nてだすけ　された　ポケモンの　技の\n威力は　いつもより　大きくなる。"}, {'id' => 280, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'かわらわり', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'かくとう', 'flavor_text' => "手刀を　勢いよく　振りおろして\n相手を　攻撃する。　ひかりのかべや\nリフレクター　なども　破壊できる。"}, {'id' => 347, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'めいそう', 'power' => nil, 'accuracy' => nil, 'pp' => 20, 'type' => 'エスパー', 'flavor_text' => "静かに　精神を　統一し\n心を　鎮めることで　自分の\n特攻と　特防を　あげる。"}],
          'damage_from' => {'normal' => 1.0, 'fighting' => 1.0, 'flying' => 0.5, 'poison' => 1.0, 'ground' => 2.0, 'rock' => 1.0, 'bug' => 1.0, 'ghost' => 1.0, 'steel' => 0.5, 'fire' => 1.0, 'water' => 1.0, 'grass' => 1.0, 'electric' => 0.5, 'psychic' => 1.0, 'ice' => 1.0, 'dragon' => 1.0, 'dark' => 1.0, 'fairy' => 1.0},
          'form_type' => nil
        }
      )
    end

    context 'get pokemon data whose version group is additional contents' do
      let(:id){ 1024 } # テラパゴス

      it do
        get api_pokemon_path(id), params: {version_group: 'scarlet-violet'}
        expect(response).to have_http_status(:success)
        expect(response.parsed_body).to match(
          {
            'damage_from' => {'bug' => 1.0, 'dark' => 1.0, 'dragon' => 1.0, 'electric' => 1.0, 'fairy' => 1.0, 'fighting' => 2.0, 'fire' => 1.0, 'flying' => 1.0, 'ghost' => 0.0, 'grass' => 1.0, 'ground' => 1.0, 'ice' => 1.0, 'normal' => 1.0, 'poison' => 1.0, 'psychic' => 1.0, 'rock' => 1.0, 'steel' => 1.0, 'water' => 1.0},
            'flavor_text' => nil,
            'id' => 1024,
            'species_id' => 1024,
            'moves' =>
              [{'id' => 110,
                'move_learn_method' => 'level-up',
                'level' => 1,
                'name' => 'からにこもる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 40,
                'type' => 'みず',
                'flavor_text' => "殻に　潜りこんで　身を守り\n自分の　防御を　あげる。"},
               {'id' => 161,
                'move_learn_method' => 'level-up',
                'level' => 1,
                'name' => 'トライアタック',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "３つの　光線で　攻撃する。\nまひか　やけどか　こおり状態の\nどれかに　することが　ある。"},
               {'id' => 229,
                'move_learn_method' => 'level-up',
                'level' => 1,
                'name' => 'こうそくスピン',
                'power' => 50,
                'accuracy' => 100,
                'pp' => 40,
                'type' => 'ノーマル',
                'flavor_text' => "回転して　相手を　攻撃する。\nしめつける　まきつく　やどりぎのタネ　など\n吹きとばす。自分の　素早さも　あがる。"},
               {'id' => 246,
                'move_learn_method' => 'level-up',
                'level' => 10,
                'name' => 'げんしのちから',
                'power' => 60,
                'accuracy' => 100,
                'pp' => 5,
                'type' => 'いわ',
                'flavor_text' => "原始の　力で　攻撃する。\n自分の　すべての\n能力が　あがることが　ある。"},
               {'id' => 29,
                'move_learn_method' => 'level-up',
                'level' => 20,
                'name' => 'ずつき',
                'power' => 70,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ノーマル',
                'flavor_text' => "頭を　突きだして\nまっすぐ　つっこんで　攻撃する。\n相手を　ひるませることが　ある。"},
               {'id' => 182,
                'move_learn_method' => 'level-up',
                'level' => 30,
                'name' => 'まもる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "相手の　攻撃を\nまったく　受けない。\n連続で　だすと　失敗しやすい。"},
               {'id' => 414,
                'move_learn_method' => 'level-up',
                'level' => 40,
                'name' => 'だいちのちから',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'じめん',
                'flavor_text' => "相手の　足下へ　大地の力を\n放出する。相手の　特防を\nさげることが　ある。"},
               {'id' => 484,
                'move_learn_method' => 'level-up',
                'level' => 50,
                'name' => 'ヘビーボンバー',
                'power' => nil,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'はがね',
                'flavor_text' => "重たい　体で　相手に　ぶつかって\n攻撃する。　自分が　相手より\n重いほど　威力が　あがる。"},
               {'id' => 906, 'move_learn_method' => 'level-up', 'level' => 60, 'name' => 'テラクラスター', 'power' => 120, 'accuracy' => 100, 'pp' => 5, 'type' => 'ノーマル', 'flavor_text' => nil},
               {'id' => 38,
                'move_learn_method' => 'level-up',
                'level' => 70,
                'name' => 'すてみタックル',
                'power' => 120,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ノーマル',
                'flavor_text' => "命を　懸けて\n相手に　突進して　攻撃する。\n自分も　かなり　ダメージを　受ける。"},
               {'id' => 397,
                'move_learn_method' => 'level-up',
                'level' => 80,
                'name' => 'ロックカット',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 20,
                'type' => 'いわ',
                'flavor_text' => "自分の　体を　磨いて　空気の\n抵抗を　少なくする。素早さを\nぐーんと　あげることが　できる。"},
               {'id' => 360,
                'move_learn_method' => 'level-up',
                'level' => 90,
                'name' => 'ジャイロボール',
                'power' => nil,
                'accuracy' => 100,
                'pp' => 5,
                'type' => 'はがね',
                'flavor_text' => "体を　高速に　回転させて\n体当たりする。相手より　素早さが\n低いほど　強い。"},
               {'id' => 34,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'のしかかり',
                'power' => 85,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ノーマル',
                'flavor_text' => "全身で\n相手に　のしかかり　攻撃する。\nまひ状態に　することが　ある。"},
               {'id' => 36,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'とっしん',
                'power' => 90,
                'accuracy' => 85,
                'pp' => 20,
                'type' => 'ノーマル',
                'flavor_text' => "すごい　勢いで\n相手に　ぶつかって　攻撃する。\n自分も　少し　ダメージを　受ける。"},
               {'id' => 38,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'すてみタックル',
                'power' => 120,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ノーマル',
                'flavor_text' => "命を　懸けて\n相手に　突進して　攻撃する。\n自分も　かなり　ダメージを　受ける。"},
               {'id' => 46,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ほえる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 20,
                'type' => 'ノーマル',
                'flavor_text' => "相手を　逃がして\n控えの　ポケモンを　ひきずりだす。\n野生の　場合は　戦闘が　終わる。"},
               {'id' => 53,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'かえんほうしゃ',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ほのお',
                'flavor_text' => "激しい　炎を\n相手に　発射して　攻撃する。\nやけど状態に　することが　ある。"},
               {'id' => 57,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'なみのり',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'みず',
                'flavor_text' => "大きな　波で　自分の\n周りに　いるものを　攻撃する。"},
               {'id' => 58,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'れいとうビーム',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'こおり',
                'flavor_text' => "凍える　ビームを\n相手に　発射して　攻撃する。\nこおり状態に　することが　ある。"},
               {'id' => 63,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'はかいこうせん',
                'power' => 150,
                'accuracy' => 90,
                'pp' => 5,
                'type' => 'ノーマル',
                'flavor_text' => "強い　光線を\n相手に　発射して　攻撃する。\n次の　ターンは　動けなくなる。"},
               {'id' => 76,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ソーラービーム',
                'power' => 120,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'くさ',
                'flavor_text' => "１ターン目に　光を　いっぱいに　集め\n２ターン目に　光の　束を\n発射して　攻撃する。"},
               {'id' => 85,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => '１０まんボルト',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'でんき',
                'flavor_text' => "強い　電撃を\n相手に　浴びせて　攻撃する。\nまひ状態に　することが　ある。"},
               {'id' => 87,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'かみなり',
                'power' => 110,
                'accuracy' => 70,
                'pp' => 10,
                'type' => 'でんき',
                'flavor_text' => "激しい　雷を\n相手に　落として　攻撃する。\nまひ状態に　することが　ある。"},
               {'id' => 89,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'じしん',
                'power' => 100,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'じめん',
                'flavor_text' => "地震の　衝撃で　自分の\n周りに　いるものを　攻撃する。"},
               {'id' => 92,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'どくどく',
                'power' => nil,
                'accuracy' => 90,
                'pp' => 10,
                'type' => 'どく',
                'flavor_text' => "相手を　猛毒の　状態に　する。\nターンが　すすむほど\n毒の　ダメージが　増えていく。"},
               {'id' => 156,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ねむる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 5,
                'type' => 'エスパー',
                'flavor_text' => "２ターンの　間　眠り続ける。\n自分の　ＨＰと　状態異常を\nすべて　回復する。"},
               {'id' => 157,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'いわなだれ',
                'power' => 75,
                'accuracy' => 90,
                'pp' => 10,
                'type' => 'いわ',
                'flavor_text' => "大きな　岩を\n激しく　ぶつけて　攻撃する。\n相手を　ひるませることが　ある。"},
               {'id' => 164,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'みがわり',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "自分の　ＨＰを　少し　削って\n分身を　だす。\n分身は　自分の　身代わりに　なる。"},
               {'id' => 182,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'まもる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "相手の　攻撃を\nまったく　受けない。\n連続で　だすと　失敗しやすい。"},
               {'id' => 203,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'こらえる',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "攻撃を　受けても\nＨＰを　必ず　１だけ　残せる。\n連続で　だすと　失敗しやすい。"},
               {'id' => 214,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ねごと',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "自分が　おぼえている　技の　うち\nどれか　１つを　くりだす。\n自分が　寝ているときだけ　使える。"},
               {'id' => 240,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'あまごい',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 5,
                'type' => 'みず',
                'flavor_text' => "５ターンの　間　雨を　降らせて\nみずタイプの　威力を　あげる。\nほのおタイプの　威力は　さがる。"},
               {'id' => 241,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'にほんばれ',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 5,
                'type' => 'ほのお',
                'flavor_text' => "５ターンの　間　日差しを　強くして\nほのおタイプの　威力を　あげる。\nみずタイプの　威力は　さがる。"},
               {'id' => 242,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'かみくだく',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'あく',
                'flavor_text' => "鋭い　歯で\n相手を　かみくだいて　攻撃する。\n相手の　防御を　さげることが　ある。"},
               {'id' => 263,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'からげんき',
                'power' => 70,
                'accuracy' => 100,
                'pp' => 20,
                'type' => 'ノーマル',
                'flavor_text' => "自分が　毒　まひ　やけど\n状態のとき　相手に　くりだすと\n技の　威力が　２倍に　なる。"},
               {'id' => 311,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ウェザーボール',
                'power' => 50,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'ノーマル',
                'flavor_text' => "使ったときの　天気に　よって\n技の　タイプと　威力が　変わる。"},
               {'id' => 347,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'めいそう',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 20,
                'type' => 'エスパー',
                'flavor_text' => "静かに　精神を　統一し\n心を　鎮めることで　自分の\n特攻と　特防を　あげる。"},
               {'id' => 352,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'みずのはどう',
                'power' => 60,
                'accuracy' => 100,
                'pp' => 20,
                'type' => 'みず',
                'flavor_text' => "水の　振動を\n相手に　与えて　攻撃する。\n相手を　混乱させることが　ある。"},
               {'id' => 356,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'じゅうりょく',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 5,
                'type' => 'エスパー',
                'flavor_text' => "５ターンの間　ふゆうや　ひこうタイプに\nじめんタイプの　技が　当たるようになる。\n空中に　飛ぶ　技も　使えない。"},
               {'id' => 360,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ジャイロボール',
                'power' => nil,
                'accuracy' => 100,
                'pp' => 5,
                'type' => 'はがね',
                'flavor_text' => "体を　高速に　回転させて\n体当たりする。相手より　素早さが\n低いほど　強い。"},
               {'id' => 394,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'フレアドライブ',
                'power' => 120,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'ほのお',
                'flavor_text' => "炎を　まとって　突進する。\n自分も　かなり　ダメージを　受ける。\nやけど状態に　することが　ある。"},
               {'id' => 396,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'はどうだん',
                'power' => 80,
                'accuracy' => nil,
                'pp' => 20,
                'type' => 'かくとう',
                'flavor_text' => "体の　奥から　波導の　力を\n相手に　うち放つ。\n攻撃は　必ず　命中する。"},
               {'id' => 399,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'あくのはどう',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'あく',
                'flavor_text' => "体から　悪意に　みちた\n恐ろしい　オーラを　発する。\n相手を　ひるませることが　ある。"},
               {'id' => 405,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'むしのさざめき',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'むし',
                'flavor_text' => "振動で　音波を　おこして\n攻撃する。相手の　特防を\nさげることが　ある。"},
               {'id' => 406,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'りゅうのはどう',
                'power' => 85,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'ドラゴン',
                'flavor_text' => "大きな　口から　衝撃波を\nまきおこして　相手を　攻撃する。"},
               {'id' => 408,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'パワージェム',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 20,
                'type' => 'いわ',
                'flavor_text' => "宝石のように　きらめく　光を\n発射して　相手を　攻撃する。"},
               {'id' => 412,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'エナジーボール',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'くさ',
                'flavor_text' => "自然から　集めた\n命の力を　発射する。\n相手の　特防を　さげることがある。"},
               {'id' => 414,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'だいちのちから',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'じめん',
                'flavor_text' => "相手の　足下へ　大地の力を\n放出する。相手の　特防を\nさげることが　ある。"},
               {'id' => 416,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ギガインパクト',
                'power' => 150,
                'accuracy' => 90,
                'pp' => 5,
                'type' => 'ノーマル',
                'flavor_text' => "持てる　力を　すべて　使って\n相手に　突撃する。\n次の　ターンは　動けなくなる。"},
               {'id' => 428,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'しねんのずつき',
                'power' => 80,
                'accuracy' => 90,
                'pp' => 15,
                'type' => 'エスパー',
                'flavor_text' => "思念の　力を\n額に　集めて　攻撃する。\n相手を　ひるませることが　ある。"},
               {'id' => 430,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ラスターカノン',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'はがね',
                'flavor_text' => "体の　光を　一点に　集めて\n力を　放つ。\n相手の　特防を　さげることが　ある。"},
               {'id' => 442,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'アイアンヘッド',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'はがね',
                'flavor_text' => "鋼の　ような\n硬い　頭で　攻撃する。\n相手を　ひるませることが　ある。"},
               {'id' => 444,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ストーンエッジ',
                'power' => 100,
                'accuracy' => 80,
                'pp' => 5,
                'type' => 'いわ',
                'flavor_text' => "とがった　岩を\n相手に　突き刺して　攻撃する。\n急所に　当たりやすい。"},
               {'id' => 446,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ステルスロック',
                'power' => nil,
                'accuracy' => nil,
                'pp' => 20,
                'type' => 'いわ',
                'flavor_text' => "相手の　周りに　無数の　岩を\n浮かべて　交代で　でてきた　相手の\nポケモンに　ダメージを　与える。"},
               {'id' => 484,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ヘビーボンバー',
                'power' => nil,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'はがね',
                'flavor_text' => "重たい　体で　相手に　ぶつかって\n攻撃する。　自分が　相手より\n重いほど　威力が　あがる。"},
               {'id' => 500,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'アシストパワー',
                'power' => 20,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'エスパー',
                'flavor_text' => "蓄積された　パワーで　相手を\n攻撃する。自分の　能力が\nあがっているほど　威力が　あがる。"},
               {'id' => 528,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ワイルドボルト',
                'power' => 90,
                'accuracy' => 100,
                'pp' => 15,
                'type' => 'でんき',
                'flavor_text' => "電気を　まとって\n相手に　ぶつかって　攻撃する。\n自分も　少し　ダメージを　受ける。"},
               {'id' => 535,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ヒートスタンプ',
                'power' => nil,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'ほのお',
                'flavor_text' => "燃える　体で　相手に　ぶつかって\n攻撃する。　自分が　相手より\n重いほど　威力が　あがる。"},
               {'id' => 605,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'マジカルシャイン',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'フェアリー',
                'flavor_text' => "強力な　光を　放ち\n相手に　ダメージを　与える。"},
               {'id' => 776,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ボディプレス',
                'power' => 80,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'かくとう',
                'flavor_text' => "体を　ぶつけて　攻撃。\n防御が　高いほど\n与える　ダメージが　増える。"},
               {'id' => 800,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'メテオビーム',
                'power' => 120,
                'accuracy' => 90,
                'pp' => 10,
                'type' => 'いわ',
                'flavor_text' => "１ターン目に　宇宙の　力を\n集めることで　特攻が　あがり\n２ターン目に　相手を　攻撃する。"},
               {'id' => 815,
                'move_learn_method' => 'machine',
                'level' => 0,
                'name' => 'ねっさのだいち',
                'power' => 70,
                'accuracy' => 100,
                'pp' => 10,
                'type' => 'じめん',
                'flavor_text' => "熱く　焼けた　砂を\n相手に　ぶつけて　攻撃する。\nやけど状態に　することが　ある。"},
               {'id' => 861, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'アイススピナー', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'こおり', 'flavor_text' => nil},
               {'id' => 916, 'move_learn_method' => 'machine', 'level' => 0, 'name' => 'サンダーダイブ', 'power' => 100, 'accuracy' => 95, 'pp' => 15, 'type' => 'でんき', 'flavor_text' => nil}],
            'name' => 'テラパゴス',
            'sprites' => {'front_default' => 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1024.png'},
            'status' => [
              {'base_stat' => 90, 'effort' => 0, 'label' => 'HP', 'name' => 'hp'},
              {'base_stat' => 65, 'effort' => 0, 'label' => 'こうげき', 'name' => 'attack'},
              {'base_stat' => 85, 'effort' => 1, 'label' => 'ぼうぎょ', 'name' => 'defense'},
              {'base_stat' => 65, 'effort' => 0, 'label' => 'とくこう', 'name' => 'special_attack'},
              {'base_stat' => 85, 'effort' => 0, 'label' => 'とくぼう', 'name' => 'special_defense'},
              {'base_stat' => 60, 'effort' => 0, 'label' => 'すばやさ', 'name' => 'speed'}
            ],
            'types' => [{'name' => 'ノーマル', 'slot' => 1}],
            'abilities' => [{'flavor_text' => nil, 'is_hidden' => false, 'name' => 'テラスチェンジ'}],
            'form_type' => nil
          }
        )
      end
    end

    context 'get pokemon data which has moves with same names' do
      let(:id) { 3 } # フシギバナ

      it do
        get api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
        expect(response).to have_http_status(:success)
        expect(response.parsed_body['moves']).to include(
          {'id' => 80, 'accuracy' => 100, 'power' => 120, 'pp' => 10, 'type' => 'くさ', 'name' => 'はなびらのまい', 'level' => 0, 'move_learn_method' => 'level-up', 'flavor_text' => "２ー３ターンの　間　花を\nまきちらして　相手を　攻撃する。\nまきちらした　あとは　混乱する。", },
          {'id' => 80, 'accuracy' => 100, 'power' => 120, 'pp' => 10, 'type' => 'くさ', 'name' => 'はなびらのまい', 'level' => 1, 'move_learn_method' => 'level-up', 'flavor_text' => "２ー３ターンの　間　花を\nまきちらして　相手を　攻撃する。\nまきちらした　あとは　混乱する。", }
        )
      end
    end

    context 'get pokemon data whose damage from has several values' do


      context 'magneton' do
        let(:id) { 82 } # レアコイル

        it do
          get api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body['damage_from']).to eq(
            {
              'bug' => 0.5,
              'dark' => 1,
              'dragon' => 0.5,
              'electric' => 0.5,
              'fairy' => 0.5,
              'fighting' => 2,
              'fire' => 2,
              'flying' => 0.25,
              'ghost' => 1,
              'grass' => 0.5,
              'ground' => 4,
              'ice' => 0.5,
              'normal' => 0.5,
              'poison' => 0,
              'psychic' => 0.5,
              'rock' => 0.5,
              'steel' => 0.25,
              'water' => 1
            }
          )
        end
      end

      context 'quagsire' do
        let(:id) { 195 } # ヌオー

        it do
          get api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body['damage_from']).to eq(
            {
              'bug' => 1,
              'dark' => 1,
              'dragon' => 1,
              'electric' => 0,
              'fairy' => 1,
              'fighting' => 1,
              'fire' => 0.5,
              'flying' => 1,
              'ghost' => 1,
              'grass' => 4,
              'ground' => 1,
              'ice' => 1,
              'normal' => 1,
              'poison' => 0.5,
              'psychic' => 1,
              'rock' => 0.5,
              'steel' => 0.5,
              'water' => 1
            }
          )
        end
      end

    end

    context 'get pokemon data when ability flavor text is empty' do
      let(:id){ 1024 } # テラパゴス

      it do
        get api_pokemon_path(id), params: {version_group: 'scarlet-violet'}
        expect(response).to have_http_status(:success)
        expect(response.parsed_body[:abilities]).to contain_exactly({'flavor_text' => nil, 'is_hidden' => false, 'name' => 'テラスチェンジ'})
      end
    end

    context 'not found error when main version group is invalid' do
      it do
        get api_pokemon_path(id), params: {version_group: 'the-teal-mask'}
        expect(response).to have_http_status(:bad_request)
      end
    end
  end

  describe '#form', :vcr do
    context 'when there are some forms' do
      let(:id) { 3 } # フシギバナ

      context 'when mega is valid' do
        it do
          get forms_api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body).to match(
            'forms' => [
              {'id' => 3, 'is_battle_only' => false, 'is_default' => true, 'name' => 'フシギバナ'},
              {'id' => 10033, 'is_battle_only' => true, 'is_default' => false, 'name' => 'メガフシギバナ'}
            ]
          )
        end
      end

      context 'when gmax is valid' do
        it do
          get forms_api_pokemon_path(id), params: {version_group: 'sword-shield'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body).to match(
            'forms' => [
              {'id' => 3, 'is_battle_only' => false, 'is_default' => true, 'name' => 'フシギバナ'},
              {'id' => 10195, 'is_battle_only' => true, 'is_default' => false, 'name' => 'キョダイマックスフシギバナ'}
            ]
          )
        end
      end

      context 'when sugata is valid in version group' do
        let(:id) { 128 } # ケンタロス

        it  do
          get forms_api_pokemon_path(id), params: {version_group: 'scarlet-violet'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body).to match(
            'forms' => [
              {'id' => 128, 'is_battle_only' => false, 'is_default' => true, 'name' => 'ケンタロス'},
              {'id' => 10250, 'is_battle_only' => false, 'is_default' => false, 'name' => 'パルデアのすがた・コンバットしゅ'},
              {'id' => 10251, 'is_battle_only' => false, 'is_default' => false, 'name' => 'パルデアのすがた・ブレイズしゅ'},
              {'id' => 10252, 'is_battle_only' => false, 'is_default' => false, 'name' => 'パルデアのすがた・ウォーターしゅ'}
            ]
          )
        end
      end

      context 'when sugata is invalid in version group' do
        let(:id) { 128 } # ケンタロス

        it  do
          get forms_api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body).to match(
            'forms' => [
              {'id' => 128, 'is_battle_only' => false, 'is_default' => true, 'name' => 'ケンタロス'}
            ]
          )
        end
      end
    end
  end

  describe '#evolution_chain', :vcr do
    let(:id) { 25 } # ピカチュウ

    it 'get evolution chain' do
      get evolution_chain_api_pokemon_path(id), params: {version_group: 'lets-go-pikachu-lets-go-eevee'}
      expect(response).to have_http_status(:success)
      expect(response.parsed_body).to match(
        {
          'evolution_chain' => {
            'evolution_details' => [],
            'evolves_to' => [
              {
                'evolution_details' => [
                  {
                    'gender' => nil,
                    'held_item' => nil,
                    'item' => nil,
                    'known_move' => nil,
                    'known_move_type' => nil,
                    'location' => nil,
                    'min_affection' => nil,
                    'min_beauty' => nil,
                    'min_happiness' => 220,
                    'min_level' => nil,
                    'needs_overworld_rain' => false,
                    'party_species' => nil,
                    'party_type' => nil,
                    'relative_physical_stats' => nil,
                    'time_of_day' => '',
                    'trade_species' => nil,
                    'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'}, 'turn_upside_down' => false
                  }
                ],
                'evolves_to' => [
                  {
                    'evolution_details' => [
                      {'gender' => nil,
                       'held_item' => nil,
                       'item' => {
                         'name' => 'thunder-stone',
                         'url' => 'https://pokeapi.co/api/v2/item/83/'
                       },
                       'known_move' => nil,
                       'known_move_type' => nil,
                       'location' => nil,
                       'min_affection' => nil,
                       'min_beauty' => nil,
                       'min_happiness' => nil,
                       'min_level' => nil,
                       'needs_overworld_rain' => false,
                       'party_species' => nil,
                       'party_type' => nil,
                       'relative_physical_stats' => nil,
                       'time_of_day' => '',
                       'trade_species' => nil,
                       'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'}, 'turn_upside_down' => false}
                    ], 'evolves_to' => [], 'id' => 26, 'is_baby' => false, 'is_in_version_group' => true, 'name' => 'ライチュウ'
                  }
                ], 'id' => 25, 'is_baby' => false, 'is_in_version_group' => true, 'name' => 'ピカチュウ'
              }
            ], 'id' => 172, 'is_baby' => true, 'is_in_version_group' => false, 'name' => 'ピチュー'
          }
        }
      )
    end

    context 'get pokemon data whose has some evolution chains' do
      let(:id){ 133 } # イーブイ

      context 'version_group is lets-go-pikachu-lets-go-eevee' do
        let(:version_group){ 'lets-go-pikachu-lets-go-eevee' }

        it do
          get evolution_chain_api_pokemon_path(id), params: {version_group: version_group}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body['evolution_chain']).to eq(
            {'id' => 133,
             'name' => 'イーブイ',
             'is_baby' => false,
             'evolution_details' => [],
             'evolves_to' =>
             [{'id' => 134,
               'name' => 'シャワーズ',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => {'name' => 'water-stone', 'url' => 'https://pokeapi.co/api/v2/item/84/'},
                  'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => true},
              {'id' => 135,
               'name' => 'サンダース',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => {'name' => 'thunder-stone', 'url' => 'https://pokeapi.co/api/v2/item/83/'},
                  'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => true},
              {'id' => 136,
               'name' => 'ブースター',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => {'name' => 'fire-stone', 'url' => 'https://pokeapi.co/api/v2/item/82/'},
                  'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => true},
              {'id' => 196,
               'name' => 'エーフィ',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => 160,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => 'day',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => false},
              {'id' => 197,
               'name' => 'ブラッキー',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => 160,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => 'night',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => false},
              {'id' => 470,
               'name' => 'リーフィア',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'eterna-forest', 'url' => 'https://pokeapi.co/api/v2/location/8/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'pinwheel-forest', 'url' => 'https://pokeapi.co/api/v2/location/375/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'kalos-route-20', 'url' => 'https://pokeapi.co/api/v2/location/650/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => {'name' => 'leaf-stone', 'url' => 'https://pokeapi.co/api/v2/item/85/'},
                  'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => false},
              {'id' => 471,
               'name' => 'グレイシア',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'sinnoh-route-217', 'url' => 'https://pokeapi.co/api/v2/location/48/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'twist-mountain', 'url' => 'https://pokeapi.co/api/v2/location/380/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => {'name' => 'frost-cavern', 'url' => 'https://pokeapi.co/api/v2/location/640/'},
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => {'name' => 'ice-stone', 'url' => 'https://pokeapi.co/api/v2/item/885/'},
                  'trigger' => {'name' => 'use-item', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/3/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => false},
              {'id' => 700,
               'name' => 'ニンフィア',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => {'name' => 'fairy', 'url' => 'https://pokeapi.co/api/v2/type/18/'},
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => 2,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false},
                 {'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => {'name' => 'fairy', 'url' => 'https://pokeapi.co/api/v2/type/18/'},
                  'location' => nil,
                  'min_level' => nil,
                  'min_happiness' => 160,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' => [],
               'is_in_version_group' => false}],
             'is_in_version_group' => true}
          )
        end
      end
    end

    context 'get pokemon data whose has some evolution chains in additional contents' do
      let(:id){ 1 } # フシギダネ
      let(:version_group){ 'scarlet-violet' }

        it do
          get evolution_chain_api_pokemon_path(id), params: {version_group: version_group}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body['evolution_chain']).to eq(
            {
              'id' => 1,
              'name' => 'フシギダネ',
              'is_baby' => false,
              'evolution_details' => [],
              'evolves_to' =>
                [{'id' => 2,
                  'name' => 'フシギソウ',
                  'is_baby' => false,
                  'evolution_details' =>
                    [{'item' => nil,
                      'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                      'gender' => nil,
                      'held_item' => nil,
                      'known_move' => nil,
                      'known_move_type' => nil,
                      'location' => nil,
                      'min_level' => 16,
                      'min_happiness' => nil,
                      'min_beauty' => nil,
                      'min_affection' => nil,
                      'needs_overworld_rain' => false,
                      'party_species' => nil,
                      'party_type' => nil,
                      'relative_physical_stats' => nil,
                      'time_of_day' => '',
                      'trade_species' => nil,
                      'turn_upside_down' => false}],
                  'evolves_to' =>
                   [{'id' => 3,
                     'name' => 'フシギバナ',
                     'is_baby' => false,
                     'evolution_details' =>
                      [{'item' => nil,
                        'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                        'gender' => nil,
                        'held_item' => nil,
                        'known_move' => nil,
                        'known_move_type' => nil,
                        'location' => nil,
                        'min_level' => 32,
                        'min_happiness' => nil,
                        'min_beauty' => nil,
                        'min_affection' => nil,
                        'needs_overworld_rain' => false,
                        'party_species' => nil,
                        'party_type' => nil,
                        'relative_physical_stats' => nil,
                        'time_of_day' => '',
                        'trade_species' => nil,
                        'turn_upside_down' => false}],
                     'evolves_to' => [],
                     'is_in_version_group' => true}],
                  'is_in_version_group' => true}],
              'is_in_version_group' => true
            }
          )
        end
    end

    context 'when pokemon id is one which is not default form' do
      let(:id){ 10033 } # メガフシギバナ
      let(:version_group){ 'lets-go-pikachu-lets-go-eevee' }

        it do
          get evolution_chain_api_pokemon_path(id), params: {version_group: version_group}
          expect(response).to have_http_status(:success)
          expect(response.parsed_body['evolution_chain']).to eq(
            {'id' => 1,
             'name' => 'フシギダネ',
             'is_baby' => false,
             'evolution_details' => [],
             'evolves_to' =>
             [{'id' => 2,
               'name' => 'フシギソウ',
               'is_baby' => false,
               'evolution_details' =>
                [{'item' => nil,
                  'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                  'gender' => nil,
                  'held_item' => nil,
                  'known_move' => nil,
                  'known_move_type' => nil,
                  'location' => nil,
                  'min_level' => 16,
                  'min_happiness' => nil,
                  'min_beauty' => nil,
                  'min_affection' => nil,
                  'needs_overworld_rain' => false,
                  'party_species' => nil,
                  'party_type' => nil,
                  'relative_physical_stats' => nil,
                  'time_of_day' => '',
                  'trade_species' => nil,
                  'turn_upside_down' => false}],
               'evolves_to' =>
                [{'id' => 3,
                  'name' => 'フシギバナ',
                  'is_baby' => false,
                  'evolution_details' =>
                   [{'item' => nil,
                     'trigger' => {'name' => 'level-up', 'url' => 'https://pokeapi.co/api/v2/evolution-trigger/1/'},
                     'gender' => nil,
                     'held_item' => nil,
                     'known_move' => nil,
                     'known_move_type' => nil,
                     'location' => nil,
                     'min_level' => 32,
                     'min_happiness' => nil,
                     'min_beauty' => nil,
                     'min_affection' => nil,
                     'needs_overworld_rain' => false,
                     'party_species' => nil,
                     'party_type' => nil,
                     'relative_physical_stats' => nil,
                     'time_of_day' => '',
                     'trade_species' => nil,
                     'turn_upside_down' => false}],
                  'evolves_to' => [],
                  'is_in_version_group' => true}],
               'is_in_version_group' => true}],
             'is_in_version_group' => true}
          )
        end
    end
  end
end
